---

- name: gather dmi.bios-vendor fact
  raw: sudo -n /usr/sbin/dmidecode -s bios-vendor
  register: dmi_bios_vendor
  ignore_errors: yes
  when: '"Dmi_dmi.bios-vendor" in facts_to_collect'

- name: add dmi.bios-vendor to dictionary
  set_fact:
    dmi: "{{ dmi|default({}) | combine({ item: dmi_bios_vendor['stdout_lines'][0] }) }}"
  with_items:
  - 'dmi.bios-vendor'

- name: gather dmi.bios-version fact
  raw: sudo -n /usr/sbin/dmidecode -s bios-version
  register: dmi_bios_version
  ignore_errors: yes
  when: '"Dmi_dmi.bios-version" in facts_to_collect'

- name: add dmi.bios-version to dictionary
  set_fact:
    dmi: "{{ dmi|default({}) | combine({ item: dmi_bios_version['stdout_lines'][0] }) }}"
  with_items:
  - 'dmi.bios-version'

- name: gather dmi.system-manufacturer fact
  raw: sudo -n /usr/sbin/dmidecode | grep -A4 'System Information' | grep 'Manufacturer' | sed -n -e 's/^.*Manufacturer:\s//p'
  register: dmi_system_manufacturer
  ignore_errors: yes
  when: '"Dmi_dmi.system-manufacturer" in facts_to_collect'

- name: add dmi.system-manufacturer to dictionary
  set_fact:
    dmi: "{{ dmi|default({}) | combine({ item: dmi_system_manufacturer['stdout'] }) }}"
  with_items:
  - 'dmi.system-manufacturer'

- name: gather processor-family fact
  raw: sudo -n /usr/sbin/dmidecode -s processor-family
  register: dmi_processor_family
  ignore_errors: yes
  when: '"Dmi_dmi.processor-family" in facts_to_collect'

- name: add dmi.processor-family to dictionary
  set_fact:
    dmi: "{{ dmi|default({}) | combine({ item: dmi_processor_family['stdout_lines'][0] }) }}"
  with_items:
  - 'dmi.processor-family'
