---

- name: initialize dmi dictionary
  set_fact:
    dmi: "{{ dmi|default({}) }}"

- name: gather dmi.bios-vendor fact
  raw: /usr/sbin/dmidecode -s bios-vendor
  register: dmi_bios_vendor
  ignore_errors: yes
  become: yes
  when: '"dmi.bios-vendor" in facts_to_collect'

- name: add dmi.bios-vendor to dictionary
  set_fact:
    dmi: "{{ dmi|default({}) | combine({ item: dmi_bios_vendor['stdout'] | trim | default('error') }) }}"
  with_items:
  - 'dmi.bios-vendor'
  when: '"dmi.bios-vendor" in facts_to_collect'

- name: gather dmi.bios-version fact
  raw: /usr/sbin/dmidecode -s bios-version
  register: dmi_bios_version
  ignore_errors: yes
  become: yes
  when: '"dmi.bios-version" in facts_to_collect'

- name: add dmi.bios-version to dictionary
  set_fact:
    dmi: "{{ dmi|default({}) | combine({ item: dmi_bios_version['stdout'] | trim | default('error') }) }}"
  with_items:
  - 'dmi.bios-version'
  when: '"dmi.bios-version" in facts_to_collect'

- name: gather dmi.system-manufacturer fact
  raw: /usr/sbin/dmidecode | grep -A4 'System Information' | grep 'Manufacturer' | sed -n -e 's/^.*Manufacturer:\s//p'
  register: dmi_system_manufacturer
  ignore_errors: yes
  become: yes
  when: '"dmi.system-manufacturer" in facts_to_collect'

- name: add dmi.system-manufacturer to dictionary
  set_fact:
    dmi: "{{ dmi|default({}) | combine({ item: dmi_system_manufacturer['stdout'] | trim | default('error') }) }}"
  with_items:
  - 'dmi.system-manufacturer'
  when: '"dmi.system-manufacturer" in facts_to_collect'

- name: gather processor-family fact
  raw: /usr/sbin/dmidecode -s processor-family
  register: dmi_processor_family
  ignore_errors: yes
  become: yes
  when: '"dmi.processor-family" in facts_to_collect'

- name: add dmi.processor-family to dictionary
  set_fact:
    dmi: "{{ dmi|default({}) | combine({ item: dmi_processor_family['stdout'] | trim | default('error') }) }}"
  with_items:
  - 'dmi.processor-family'
  when: '"dmi.processor-family" in facts_to_collect'
