
---
    - name: Gather jboss.eap.running-paths
      raw: for proc_pid in $(find /proc -maxdepth 1 -xdev -name "[0-9]*"); do ls -l ${proc_pid}/fd 2>/dev/null | grep "java"; done | grep -e "/modules/system/layers/base\|/opt/rh/eap" | sed -n "s/.*\->//p" | sed -n 's/\/modules\/system\/layers\/base.*//p;s/.*\(\/opt\/rh\/eap[1-9]\).*/\1/p' | sort -u
      register: jboss.eap.running-paths
      ignore_errors: yes
      when: 'have_java and "jboss.eap.running-paths" in facts_to_collect'
    - name: check for user 'jboss'
      raw: id -u jboss
      register: jboss_eap_id_jboss
      ignore_errors: yes
      when: '"jboss.eap.jboss-user" in facts_to_collect'
    - name: check for common install files and directories
      raw: test -e "{{ item }}"
      register: jboss_eap_common_files
      ignore_errors: yes
      with_items:
        - /app/jboss
        - /app/jboss6
        - /home/jboss/EAP
        - /home/jboss/EAP-6.3
        - /JBossAS
        - /JBossEAP
        - /opt/app/jboss
        - /opt/deploy/jboss
        - /opt/hpom/share/jboss
        - /opt/jboss
        - /opt/rh/eap7
        - /usr/local/jee/jboss
        - /usr/log/jboss-as
        - /usr/share/jbossas
        - /var/log/jboss-as
        - /opt/deploy/jboss/jbossas6/jboss-modules.jar
        - /usr/share/java/jboss-modules.jar
        - /usr/share/jbossas/jboss-modules.jar
      when: '"jboss.eap.common-files" in facts_to_collect'
    - name: gather jboss.eap.processes
      raw: ps -A -f e | grep eap
      register: jboss.eap.processes
      ignore_errors: yes
      when: '"jboss.eap.processes" in facts_to_collect'
    - name: check for jboss packages
      raw: rpm -qa --qf "%{NAME}|%{VERSION}|%{RELEASE}|%{INSTALLTIME}|%{VENDOR}|%{BUILDTIME}|%{BUILDHOST}|%{SOURCERPM}|%{LICENSE}|%{PACKAGER}|%{INSTALLTIME:date}|%{BUILDTIME:date}\n" | grep -E '(eap7)|(jbossas)' | sort
      register: jboss.eap.packages
      ignore_errors: yes
      when: '"jboss.eap.packages" in facts_to_collect'
