---
# This role is based on the jboss-standalone role from the Ansible
# examples, but it includes only the parts we need to test Rho.

- name: Install unzip
  yum: 
    name: unzip
    state: present
  become: yes
  become_user: root

- name: Download JBoss from jboss.org
  get_url: 
    url: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip 
    dest: /opt/jboss-as-7.1.1.Final.zip
  become: yes
  become_user: root

- name: Extract archive
  unarchive: 
    dest: /usr/share 
    src: /opt/jboss-as-7.1.1.Final.zip 
    creates: /usr/share/jboss-as 
    copy: no 
  become: yes
  become_user: root
