---

- name: collect requested facts
  run_cmds:
    name: scanner
    fact_names: "{{facts_to_collect}}"
    host: "{{ansible_host}}"
    port: "{{ansible_ssh_port}}"
  register: facts_all

- name: record host returned dictionary
  set_fact:
    res={{facts_all.meta}}
